# -*- coding: utf-8 -*-
"""
Created on Tue Sep 21 14:49:46 2021

@author: mrobinson2
"""
feature_list = ['mocap_col_average_Pelvis_T8_z',
 'mocap_col_average_jRightHip_z',
 'mocap_col_average_jLeftHip_z',
 'mocap_col_average_jRightKnee_z',
 'mocap_col_average_jLeftKnee_z',
 'mocap_col_average_jRightAnkle_z',
 'mocap_col_average_jLeftAnkle_z',
 'mocap_rmsquare_Pelvis_T8_y',
 'mocap_rmsquare_Pelvis_T8_x',
 'mocap_col_var_Pelvis_T8_z',
 'mocap_col_var_jRightHip_z',
 'mocap_col_var_jLeftHip_z',
 'mocap_col_var_jRightKnee_z',
 'mocap_col_var_jLeftKnee_z',
 'mocap_col_var_jRightAnkle_z',
 'mocap_col_var_jLeftAnkle_z',
 'mocap_two_col_ratio_Pelvis_T8_z_jRightHip_z',
 'mocap_two_col_ratio_Pelvis_T8_z_jLeftHip_z',
 'mocap_sparc_angvel_Pelvis_T8',
 'mocap_sparc_angvel_jRightHip',
 'mocap_sparc_angvel_jLeftHip',
 'mocap_sparc_angvel_T8_RightUpperArm',
 'mocap_sparc_angvel_T8_LeftUpperArm',
 'mocap_DRP_1_Pelvis_T8_z_jRightHip_z',
 'mocap_DRP_2_Pelvis_T8_z_jRightHip_z',
 'mocap_DRP_3_Pelvis_T8_z_jRightHip_z',
 'mocap_rmsquare_T8_acc_x',
 'mocap_rmsquare_T8_acc_y',
 'mocap_rmsquare_T8_acc_z',
 'mocap_angvel_rmsquare_Pelvis_T8_z',
 'mocap_angvel_rmsquare_Pelvis_T8_y',
 'mocap_angvel_rmsquare_Pelvis_T8_x',
 'mocap_angacc_rmsquare_Pelvis_T8_z',
 'mocap_angacc_rmsquare_Pelvis_T8_y',
 'mocap_angacc_rmsquare_Pelvis_T8_x',
 'mocap_dimensionless_jerk2_angvel_Pelvis_T8',
 'mocap_dimensionless_jerk2_angvel_jRightHip',
 'mocap_dimensionless_jerk2_angvel_jLeftHip',
 'mocap_shannon_entropy_Pelvis_T8_z',
 'mocap_shannon_entropy_jRightHip_z',
 'mocap_shannon_entropy_jLeftHip_z',
 'mocap_col_autocorr_Pelvis_T8_z',
 'mocap_col_autocorr_jRightHip_z',
 'mocap_col_autocorr_jLeftHip_z',
 'mocap_col_skew_Pelvis_T8_z',
 'mocap_col_skew_jRightHip_z',
 'mocap_col_skew_jLeftHip_z',
 'mocap_col_kurtosis_Pelvis_T8_z',
 'mocap_col_kurtosis_jRightHip_z',
 'mocap_col_kurtosis_jLeftHip_z',
 'mocap_time_taken_s',
 'mocap_two_col_norm_CoG_x_CoG_y',
 'mocap_quantile_01_Pelvis_T8_z',
 'mocap_quantile_01_jRightHip_z',
 'mocap_quantile_01_jLeftHip_z',
 'mocap_quantile_025_Pelvis_T8_z',
 'mocap_quantile_025_jRightHip_z',
 'mocap_quantile_025_jLeftHip_z',
 'mocap_quantile_05_Pelvis_T8_z',
 'mocap_quantile_05_jRightHip_z',
 'mocap_quantile_05_jLeftHip_z',
 'mocap_quantile_075_Pelvis_T8_z',
 'mocap_quantile_075_jRightHip_z',
 'mocap_quantile_075_jLeftHip_z',
 'mocap_quantile_09_Pelvis_T8_z',
 'mocap_quantile_09_jRightHip_z',
 'mocap_quantile_09_jLeftHip_z',
 'emg_spectral_ind_ratio_L1 Erector Spinae LEFT_1div0',
 'emg_spectral_ind_ratio_L1 Erector Spinae LEFT_-1div5',
 'emg_spectral_ind_ratio_L3 Erector Spinae LEFT_1div0',
 'emg_spectral_ind_ratio_L3 Erector Spinae LEFT_-1div5',
 'emg_spectral_ind_ratio_L5 Multifidus LEFT_1div0',
 'emg_spectral_ind_ratio_L5 Multifidus LEFT_-1div5',
 'emg_spectral_ind_ratio_L1 Erector Spinae RIGHT_1div0',
 'emg_spectral_ind_ratio_L1 Erector Spinae RIGHT_-1div5',
 'emg_spectral_ind_ratio_L3 Erector Spinae RIGHT_1div0',
 'emg_spectral_ind_ratio_L3 Erector Spinae RIGHT_-1div5',
 'emg_spectral_ind_ratio_L5 Multifidus RIGHT_1div0',
 'emg_spectral_ind_ratio_L5 Multifidus RIGHT_-1div5',
 'emg_spectral_ind_ratio_Rectus Abdominis RIGHT_1div0',
 'emg_spectral_ind_ratio_Rectus Abdominis RIGHT_-1div5',
 'emg_spectral_ind_ratio_Rectus Abdominis LEFT_1div0',
 'emg_spectral_ind_ratio_Rectus Abdominis LEFT_-1div5',
 'emg_spectral_ind_ratio_External Oblique RIGHT_1div0',
 'emg_spectral_ind_ratio_External Oblique RIGHT_-1div5',
 'emg_spectral_ind_ratio_External Oblique LEFT_1div0',
 'emg_spectral_ind_ratio_External Oblique LEFT_-1div5',
 'emg_shannon_entropy_L1 Erector Spinae LEFT',
 'emg_shannon_entropy_L3 Erector Spinae LEFT',
 'emg_shannon_entropy_L5 Multifidus LEFT',
 'emg_shannon_entropy_L1 Erector Spinae RIGHT',
 'emg_shannon_entropy_L3 Erector Spinae RIGHT',
 'emg_shannon_entropy_L5 Multifidus RIGHT',
 'emg_shannon_entropy_Rectus Abdominis RIGHT',
 'emg_shannon_entropy_External Oblique RIGHT',
 'emg_shannon_entropy_Rectus Abdominis LEFT',
 'emg_shannon_entropy_External Oblique LEFT',
 'emg_col_autocorr_L1 Erector Spinae LEFT',
 'emg_col_autocorr_L3 Erector Spinae LEFT',
 'emg_col_autocorr_L5 Multifidus LEFT',
 'emg_col_autocorr_L1 Erector Spinae RIGHT',
 'emg_col_autocorr_L3 Erector Spinae RIGHT',
 'emg_col_autocorr_L5 Multifidus RIGHT',
 'emg_col_autocorr_Rectus Abdominis RIGHT',
 'emg_col_autocorr_External Oblique RIGHT',
 'emg_col_autocorr_Rectus Abdominis LEFT',
 'emg_col_autocorr_External Oblique LEFT',
 'env_two_col_ratio_L1 Erector Spinae LEFT_Rectus Abdominis RIGHT',
 'env_two_col_ratio_L3 Erector Spinae LEFT_Rectus Abdominis RIGHT',
 'env_two_col_ratio_L5 Multifidus LEFT_Rectus Abdominis RIGHT',
 'env_two_col_ratio_L1 Erector Spinae RIGHT_Rectus Abdominis LEFT',
 'env_two_col_ratio_L3 Erector Spinae RIGHT_Rectus Abdominis LEFT',
 'env_two_col_ratio_L5 Multifidus RIGHT_Rectus Abdominis LEFT',
 'env_two_col_ratio_L1 Erector Spinae LEFT_External Oblique RIGHT',
 'env_two_col_ratio_L3 Erector Spinae LEFT_External Oblique RIGHT',
 'env_two_col_ratio_L5 Multifidus LEFT_External Oblique RIGHT',
 'env_two_col_ratio_L1 Erector Spinae RIGHT_External Oblique LEFT',
 'env_two_col_ratio_L3 Erector Spinae RIGHT_External Oblique LEFT',
 'env_two_col_ratio_L5 Multifidus RIGHT_External Oblique LEFT',
 'env_col_var_L1 Erector Spinae LEFT',
 'env_col_var_L3 Erector Spinae LEFT',
 'env_col_var_L5 Multifidus LEFT',
 'env_col_var_L1 Erector Spinae RIGHT',
 'env_col_var_L3 Erector Spinae RIGHT',
 'env_col_var_L5 Multifidus RIGHT',
 'env_col_var_Rectus Abdominis RIGHT',
 'env_col_var_Rectus Abdominis LEFT',
 'env_col_var_External Oblique LEFT',
 'env_col_average_L1 Erector Spinae LEFT',
 'env_col_average_L1 Erector Spinae RIGHT',
 'env_col_average_L3 Erector Spinae LEFT',
 'env_col_average_L3 Erector Spinae RIGHT',
 'env_col_average_L5 Multifidus LEFT',
 'env_col_average_L5 Multifidus RIGHT',
 'env_col_average_Rectus Abdominis RIGHT',
 'env_col_average_Rectus Abdominis LEFT',
 'env_col_average_External Oblique RIGHT',
 'env_col_average_External Oblique LEFT',
 'env_col_kurtosis_L1 Erector Spinae LEFT',
 'env_col_kurtosis_L1 Erector Spinae RIGHT',
 'env_col_kurtosis_L3 Erector Spinae LEFT',
 'env_col_kurtosis_L3 Erector Spinae RIGHT',
 'env_col_kurtosis_L5 Multifidus LEFT',
 'env_col_kurtosis_L5 Multifidus RIGHT',
 'env_col_kurtosis_Rectus Abdominis RIGHT',
 'env_col_kurtosis_Rectus Abdominis LEFT',
 'env_col_kurtosis_External Oblique RIGHT',
 'env_col_kurtosis_External Oblique LEFT',
 'env_col_skew_L1 Erector Spinae LEFT',
 'env_col_skew_L1 Erector Spinae RIGHT',
 'env_col_skew_L3 Erector Spinae LEFT',
 'env_col_skew_L3 Erector Spinae RIGHT',
 'env_col_skew_L5 Multifidus LEFT',
 'env_col_skew_L5 Multifidus RIGHT',
 'env_col_skew_Rectus Abdominis RIGHT',
 'env_col_skew_Rectus Abdominis LEFT',
 'env_col_skew_External Oblique RIGHT',
 'env_col_skew_External Oblique LEFT',
 'env_shannon_entropy_L1 Erector Spinae LEFT',
 'env_shannon_entropy_L1 Erector Spinae RIGHT',
 'env_shannon_entropy_L3 Erector Spinae LEFT',
 'env_shannon_entropy_L3 Erector Spinae RIGHT',
 'env_shannon_entropy_L5 Multifidus LEFT',
 'env_shannon_entropy_L5 Multifidus RIGHT',
 'env_shannon_entropy_Rectus Abdominis RIGHT',
 'env_shannon_entropy_Rectus Abdominis LEFT',
 'env_shannon_entropy_External Oblique RIGHT',
 'env_shannon_entropy_External Oblique LEFT',
 'env_col_autocorr_L1 Erector Spinae LEFT',
 'env_col_autocorr_L1 Erector Spinae RIGHT',
 'env_col_autocorr_L3 Erector Spinae LEFT',
 'env_col_autocorr_L3 Erector Spinae RIGHT',
 'env_col_autocorr_L5 Multifidus LEFT',
 'env_col_autocorr_L5 Multifidus RIGHT',
 'env_col_autocorr_Rectus Abdominis RIGHT',
 'env_col_autocorr_Rectus Abdominis LEFT',
 'env_col_autocorr_External Oblique RIGHT',
 'env_col_autocorr_External Oblique LEFT',
 'env_quantile_01_L1 Erector Spinae RIGHT',
 'env_quantile_01_L3 Erector Spinae LEFT',
 'env_quantile_01_L3 Erector Spinae RIGHT',
 'env_quantile_01_L5 Multifidus LEFT',
 'env_quantile_01_L5 Multifidus RIGHT',
 'env_quantile_01_Rectus Abdominis RIGHT',
 'env_quantile_01_Rectus Abdominis LEFT',
 'env_quantile_01_External Oblique RIGHT',
 'env_quantile_01_External Oblique LEFT',
 'env_quantile_025_L1 Erector Spinae RIGHT',
 'env_quantile_025_L3 Erector Spinae LEFT',
 'env_quantile_025_L3 Erector Spinae RIGHT',
 'env_quantile_025_L5 Multifidus LEFT',
 'env_quantile_025_L5 Multifidus RIGHT',
 'env_quantile_025_Rectus Abdominis RIGHT',
 'env_quantile_025_Rectus Abdominis LEFT',
 'env_quantile_025_External Oblique RIGHT',
 'env_quantile_025_External Oblique LEFT',
 'env_quantile_05_L1 Erector Spinae RIGHT',
 'env_quantile_05_L3 Erector Spinae LEFT',
 'env_quantile_05_L3 Erector Spinae RIGHT',
 'env_quantile_05_L5 Multifidus LEFT',
 'env_quantile_05_L5 Multifidus RIGHT',
 'env_quantile_05_Rectus Abdominis RIGHT',
 'env_quantile_05_Rectus Abdominis LEFT',
 'env_quantile_05_External Oblique RIGHT',
 'env_quantile_05_External Oblique LEFT',
 'env_quantile_075_L1 Erector Spinae RIGHT',
 'env_quantile_075_L3 Erector Spinae LEFT',
 'env_quantile_075_L3 Erector Spinae RIGHT',
 'env_quantile_075_L5 Multifidus LEFT',
 'env_quantile_075_L5 Multifidus RIGHT',
 'env_quantile_075_Rectus Abdominis RIGHT',
 'env_quantile_075_Rectus Abdominis LEFT',
 'env_quantile_075_External Oblique RIGHT',
 'env_quantile_075_External Oblique LEFT',
 'env_quantile_09_L1 Erector Spinae RIGHT',
 'env_quantile_09_L3 Erector Spinae LEFT',
 'env_quantile_09_L3 Erector Spinae RIGHT',
 'env_quantile_09_L5 Multifidus LEFT',
 'env_quantile_09_L5 Multifidus RIGHT',
 'env_quantile_09_Rectus Abdominis RIGHT',
 'env_quantile_09_Rectus Abdominis LEFT',
 'env_quantile_09_External Oblique RIGHT',
 'env_quantile_09_External Oblique LEFT',
 'env_col_max_L1 Erector Spinae LEFT',
 'env_col_max_L3 Erector Spinae LEFT',
 'env_col_max_L5 Multifidus LEFT',
 'env_col_max_L1 Erector Spinae RIGHT',
 'env_col_max_L3 Erector Spinae RIGHT',
 'env_col_max_L5 Multifidus RIGHT',
 'env_col_max_Rectus Abdominis RIGHT',
 'env_col_max_Rectus Abdominis LEFT',
 'env_col_max_External Oblique LEFT',
 'mocap_env_two_df_mult_Pelvis_T8_z_L3 Erector Spinae LEFT',
 'mocap_env_two_df_mult_Pelvis_T8_z_L3 Erector Spinae RIGHT',
 'mocap_env_two_df_mult_Pelvis_T8_z_L1 Erector Spinae LEFT',
 'mocap_env_two_df_mult_Pelvis_T8_z_L1 Erector Spinae RIGHT',
 'mocap_env_two_df_mult_Pelvis_T8_z_L5 Multifidus LEFT',
 'mocap_env_two_df_mult_Pelvis_T8_z_L5 Multifidus RIGHT',
 'emg_shift_spectral_ind_ratio_L1 Erector Spinae LEFT_1div0',
 'emg_shift_spectral_ind_ratio_L1 Erector Spinae LEFT_-1div5',
 'emg_shift_spectral_ind_ratio_L3 Erector Spinae LEFT_1div0',
 'emg_shift_spectral_ind_ratio_L3 Erector Spinae LEFT_-1div5',
 'emg_shift_spectral_ind_ratio_L5 Multifidus LEFT_1div0',
 'emg_shift_spectral_ind_ratio_L5 Multifidus LEFT_-1div5',
 'emg_shift_spectral_ind_ratio_L1 Erector Spinae RIGHT_1div0',
 'emg_shift_spectral_ind_ratio_L1 Erector Spinae RIGHT_-1div5',
 'emg_shift_spectral_ind_ratio_L3 Erector Spinae RIGHT_1div0',
 'emg_shift_spectral_ind_ratio_L3 Erector Spinae RIGHT_-1div5',
 'emg_shift_spectral_ind_ratio_L5 Multifidus RIGHT_1div0',
 'emg_shift_spectral_ind_ratio_L5 Multifidus RIGHT_-1div5',
 'emg_shift_spectral_ind_ratio_Rectus Abdominis RIGHT_1div0',
 'emg_shift_spectral_ind_ratio_Rectus Abdominis RIGHT_-1div5',
 'emg_shift_spectral_ind_ratio_Rectus Abdominis LEFT_1div0',
 'emg_shift_spectral_ind_ratio_Rectus Abdominis LEFT_-1div5',
 'emg_shift_spectral_ind_ratio_External Oblique RIGHT_1div0',
 'emg_shift_spectral_ind_ratio_External Oblique RIGHT_-1div5',
 'emg_shift_spectral_ind_ratio_External Oblique LEFT_1div0',
 'emg_shift_spectral_ind_ratio_External Oblique LEFT_-1div5',
 'emg_shift_shannon_entropy_L1 Erector Spinae LEFT',
 'emg_shift_shannon_entropy_L3 Erector Spinae LEFT',
 'emg_shift_shannon_entropy_L5 Multifidus LEFT',
 'emg_shift_shannon_entropy_L1 Erector Spinae RIGHT',
 'emg_shift_shannon_entropy_L3 Erector Spinae RIGHT',
 'emg_shift_shannon_entropy_L5 Multifidus RIGHT',
 'emg_shift_shannon_entropy_Rectus Abdominis RIGHT',
 'emg_shift_shannon_entropy_External Oblique RIGHT',
 'emg_shift_shannon_entropy_Rectus Abdominis LEFT',
 'emg_shift_shannon_entropy_External Oblique LEFT',
 'emg_shift_col_autocorr_L1 Erector Spinae LEFT',
 'emg_shift_col_autocorr_L3 Erector Spinae LEFT',
 'emg_shift_col_autocorr_L5 Multifidus LEFT',
 'emg_shift_col_autocorr_L1 Erector Spinae RIGHT',
 'emg_shift_col_autocorr_L3 Erector Spinae RIGHT',
 'emg_shift_col_autocorr_L5 Multifidus RIGHT',
 'emg_shift_col_autocorr_Rectus Abdominis RIGHT',
 'emg_shift_col_autocorr_External Oblique RIGHT',
 'emg_shift_col_autocorr_Rectus Abdominis LEFT',
 'emg_shift_col_autocorr_External Oblique LEFT',
 'env_shift_two_col_ratio_L1 Erector Spinae LEFT_Rectus Abdominis RIGHT',
 'env_shift_two_col_ratio_L3 Erector Spinae LEFT_Rectus Abdominis RIGHT',
 'env_shift_two_col_ratio_L5 Multifidus LEFT_Rectus Abdominis RIGHT',
 'env_shift_two_col_ratio_L1 Erector Spinae RIGHT_Rectus Abdominis LEFT',
 'env_shift_two_col_ratio_L3 Erector Spinae RIGHT_Rectus Abdominis LEFT',
 'env_shift_two_col_ratio_L5 Multifidus RIGHT_Rectus Abdominis LEFT',
 'env_shift_two_col_ratio_L1 Erector Spinae LEFT_External Oblique RIGHT',
 'env_shift_two_col_ratio_L3 Erector Spinae LEFT_External Oblique RIGHT',
 'env_shift_two_col_ratio_L5 Multifidus LEFT_External Oblique RIGHT',
 'env_shift_two_col_ratio_L1 Erector Spinae RIGHT_External Oblique LEFT',
 'env_shift_two_col_ratio_L3 Erector Spinae RIGHT_External Oblique LEFT',
 'env_shift_two_col_ratio_L5 Multifidus RIGHT_External Oblique LEFT',
 'env_shift_col_var_L1 Erector Spinae LEFT',
 'env_shift_col_var_L3 Erector Spinae LEFT',
 'env_shift_col_var_L5 Multifidus LEFT',
 'env_shift_col_var_L1 Erector Spinae RIGHT',
 'env_shift_col_var_L3 Erector Spinae RIGHT',
 'env_shift_col_var_L5 Multifidus RIGHT',
 'env_shift_col_var_Rectus Abdominis RIGHT',
 'env_shift_col_var_Rectus Abdominis LEFT',
 'env_shift_col_var_External Oblique LEFT',
 'env_shift_col_average_L1 Erector Spinae LEFT',
 'env_shift_col_average_L1 Erector Spinae RIGHT',
 'env_shift_col_average_L3 Erector Spinae LEFT',
 'env_shift_col_average_L3 Erector Spinae RIGHT',
 'env_shift_col_average_L5 Multifidus LEFT',
 'env_shift_col_average_L5 Multifidus RIGHT',
 'env_shift_col_average_Rectus Abdominis RIGHT',
 'env_shift_col_average_Rectus Abdominis LEFT',
 'env_shift_col_average_External Oblique RIGHT',
 'env_shift_col_average_External Oblique LEFT',
 'env_shift_col_kurtosis_L1 Erector Spinae LEFT',
 'env_shift_col_kurtosis_L1 Erector Spinae RIGHT',
 'env_shift_col_kurtosis_L3 Erector Spinae LEFT',
 'env_shift_col_kurtosis_L3 Erector Spinae RIGHT',
 'env_shift_col_kurtosis_L5 Multifidus LEFT',
 'env_shift_col_kurtosis_L5 Multifidus RIGHT',
 'env_shift_col_kurtosis_Rectus Abdominis RIGHT',
 'env_shift_col_kurtosis_Rectus Abdominis LEFT',
 'env_shift_col_kurtosis_External Oblique RIGHT',
 'env_shift_col_kurtosis_External Oblique LEFT',
 'env_shift_col_skew_L1 Erector Spinae LEFT',
 'env_shift_col_skew_L1 Erector Spinae RIGHT',
 'env_shift_col_skew_L3 Erector Spinae LEFT',
 'env_shift_col_skew_L3 Erector Spinae RIGHT',
 'env_shift_col_skew_L5 Multifidus LEFT',
 'env_shift_col_skew_L5 Multifidus RIGHT',
 'env_shift_col_skew_Rectus Abdominis RIGHT',
 'env_shift_col_skew_Rectus Abdominis LEFT',
 'env_shift_col_skew_External Oblique RIGHT',
 'env_shift_col_skew_External Oblique LEFT',
 'env_shift_shannon_entropy_L1 Erector Spinae LEFT',
 'env_shift_shannon_entropy_L1 Erector Spinae RIGHT',
 'env_shift_shannon_entropy_L3 Erector Spinae LEFT',
 'env_shift_shannon_entropy_L3 Erector Spinae RIGHT',
 'env_shift_shannon_entropy_L5 Multifidus LEFT',
 'env_shift_shannon_entropy_L5 Multifidus RIGHT',
 'env_shift_shannon_entropy_Rectus Abdominis RIGHT',
 'env_shift_shannon_entropy_Rectus Abdominis LEFT',
 'env_shift_shannon_entropy_External Oblique RIGHT',
 'env_shift_shannon_entropy_External Oblique LEFT',
 'env_shift_col_autocorr_L1 Erector Spinae LEFT',
 'env_shift_col_autocorr_L1 Erector Spinae RIGHT',
 'env_shift_col_autocorr_L3 Erector Spinae LEFT',
 'env_shift_col_autocorr_L3 Erector Spinae RIGHT',
 'env_shift_col_autocorr_L5 Multifidus LEFT',
 'env_shift_col_autocorr_L5 Multifidus RIGHT',
 'env_shift_col_autocorr_Rectus Abdominis RIGHT',
 'env_shift_col_autocorr_Rectus Abdominis LEFT',
 'env_shift_col_autocorr_External Oblique RIGHT',
 'env_shift_col_autocorr_External Oblique LEFT',
 'env_shift_quantile_01_L1 Erector Spinae RIGHT',
 'env_shift_quantile_01_L3 Erector Spinae LEFT',
 'env_shift_quantile_01_L3 Erector Spinae RIGHT',
 'env_shift_quantile_01_L5 Multifidus LEFT',
 'env_shift_quantile_01_L5 Multifidus RIGHT',
 'env_shift_quantile_01_Rectus Abdominis RIGHT',
 'env_shift_quantile_01_Rectus Abdominis LEFT',
 'env_shift_quantile_01_External Oblique RIGHT',
 'env_shift_quantile_01_External Oblique LEFT',
 'env_shift_quantile_025_L1 Erector Spinae RIGHT',
 'env_shift_quantile_025_L3 Erector Spinae LEFT',
 'env_shift_quantile_025_L3 Erector Spinae RIGHT',
 'env_shift_quantile_025_L5 Multifidus LEFT',
 'env_shift_quantile_025_L5 Multifidus RIGHT',
 'env_shift_quantile_025_Rectus Abdominis RIGHT',
 'env_shift_quantile_025_Rectus Abdominis LEFT',
 'env_shift_quantile_025_External Oblique RIGHT',
 'env_shift_quantile_025_External Oblique LEFT',
 'env_shift_quantile_05_L1 Erector Spinae RIGHT',
 'env_shift_quantile_05_L3 Erector Spinae LEFT',
 'env_shift_quantile_05_L3 Erector Spinae RIGHT',
 'env_shift_quantile_05_L5 Multifidus LEFT',
 'env_shift_quantile_05_L5 Multifidus RIGHT',
 'env_shift_quantile_05_Rectus Abdominis RIGHT',
 'env_shift_quantile_05_Rectus Abdominis LEFT',
 'env_shift_quantile_05_External Oblique RIGHT',
 'env_shift_quantile_05_External Oblique LEFT',
 'env_shift_quantile_075_L1 Erector Spinae RIGHT',
 'env_shift_quantile_075_L3 Erector Spinae LEFT',
 'env_shift_quantile_075_L3 Erector Spinae RIGHT',
 'env_shift_quantile_075_L5 Multifidus LEFT',
 'env_shift_quantile_075_L5 Multifidus RIGHT',
 'env_shift_quantile_075_Rectus Abdominis RIGHT',
 'env_shift_quantile_075_Rectus Abdominis LEFT',
 'env_shift_quantile_075_External Oblique RIGHT',
 'env_shift_quantile_075_External Oblique LEFT',
 'env_shift_quantile_09_L1 Erector Spinae RIGHT',
 'env_shift_quantile_09_L3 Erector Spinae LEFT',
 'env_shift_quantile_09_L3 Erector Spinae RIGHT',
 'env_shift_quantile_09_L5 Multifidus LEFT',
 'env_shift_quantile_09_L5 Multifidus RIGHT',
 'env_shift_quantile_09_Rectus Abdominis RIGHT',
 'env_shift_quantile_09_Rectus Abdominis LEFT',
 'env_shift_quantile_09_External Oblique RIGHT',
 'env_shift_quantile_09_External Oblique LEFT',
 'env_shift_col_max_L1 Erector Spinae LEFT',
 'env_shift_col_max_L3 Erector Spinae LEFT',
 'env_shift_col_max_L5 Multifidus LEFT',
 'env_shift_col_max_L1 Erector Spinae RIGHT',
 'env_shift_col_max_L3 Erector Spinae RIGHT',
 'env_shift_col_max_L5 Multifidus RIGHT',
 'env_shift_col_max_Rectus Abdominis RIGHT',
 'env_shift_col_max_Rectus Abdominis LEFT',
 'env_shift_col_max_External Oblique LEFT',
 'mocap_env_shift_two_df_mult_Pelvis_T8_z_L3 Erector Spinae LEFT',
 'mocap_env_shift_two_df_mult_Pelvis_T8_z_L3 Erector Spinae RIGHT',
 'mocap_env_shift_two_df_mult_Pelvis_T8_z_L1 Erector Spinae LEFT',
 'mocap_env_shift_two_df_mult_Pelvis_T8_z_L1 Erector Spinae RIGHT',
 'mocap_env_shift_two_df_mult_Pelvis_T8_z_L5 Multifidus LEFT',
 'mocap_env_shift_two_df_mult_Pelvis_T8_z_L5 Multifidus RIGHT']